// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-redesign/CleanProfessional.tsx": () => import("../components/mockups/home-redesign/CleanProfessional.tsx"),
  "./components/mockups/home-redesign/CommandBriefing.tsx": () => import("../components/mockups/home-redesign/CommandBriefing.tsx"),
  "./components/mockups/home-redesign/ManhaFresca.tsx": () => import("../components/mockups/home-redesign/ManhaFresca.tsx"),
  "./components/mockups/home-redesign/MidnightDispatch.tsx": () => import("../components/mockups/home-redesign/MidnightDispatch.tsx"),
  "./components/mockups/home-redesign/NoiteMediterranica.tsx": () => import("../components/mockups/home-redesign/NoiteMediterranica.tsx"),
  "./components/mockups/home-redesign/OrganicDashboard.tsx": () => import("../components/mockups/home-redesign/OrganicDashboard.tsx"),
  "./components/mockups/home-redesign/QliqloqDark.tsx": () => import("../components/mockups/home-redesign/QliqloqDark.tsx"),
  "./components/mockups/home-redesign/SunnyBalanced.tsx": () => import("../components/mockups/home-redesign/SunnyBalanced.tsx"),
  "./components/mockups/home-redesign/SunnyFieldwork.tsx": () => import("../components/mockups/home-redesign/SunnyFieldwork.tsx"),
  "./components/mockups/home-redesign/SunnyPolished.tsx": () => import("../components/mockups/home-redesign/SunnyPolished.tsx"),
  "./components/mockups/home-redesign/TerraQuente.tsx": () => import("../components/mockups/home-redesign/TerraQuente.tsx"),
  "./components/mockups/home-redesign/TimelineJourney.tsx": () => import("../components/mockups/home-redesign/TimelineJourney.tsx")
};
