// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-redesign/CommandBriefing.tsx": () => import("../components/mockups/home-redesign/CommandBriefing.tsx"),
  "./components/mockups/home-redesign/OrganicDashboard.tsx": () => import("../components/mockups/home-redesign/OrganicDashboard.tsx"),
  "./components/mockups/home-redesign/TimelineJourney.tsx": () => import("../components/mockups/home-redesign/TimelineJourney.tsx")
};
