const { Pool } = require('pg');
const pool = new Pool({ connectionString: 'postgresql://postgres:PtIDPDMjqoffzYzXRSJoGwZYjlPlXDsy@tramway.proxy.rlwy.net:58274/railway' });

const USER_ID = '55699098-1094-49e0-92bb-2dc0ad3e2a53';

const clients = [
  {
    name: 'Maria Conceição Ferreira',
    email: 'maria.ferreira@gmail.com',
    phone: '+351 916 234 567',
    whatsapp: '+351 916 234 567',
    address: 'Rua das Amendoeiras 12, Almancil, Loulé',
    latitude: 37.0725, longitude: -8.0108,
    has_garden: true, has_pool: true, has_jacuzzi: false,
    garden_visit_frequency: 'seasonal', pool_visit_frequency: 'seasonal', jacuzzi_visit_frequency: 'seasonal',
    pool_length: 8.0, pool_width: 4.0, pool_min_depth: 1.2, pool_max_depth: 2.0,
    service_duration_minutes: 90,
    notes: 'Jardim com roseiras e oliveiras. Piscina rectangular. Portão automático.',
    billing_type: 'monthly', monthly_rate: 150.00, payment_method: 'mbway', preferred_language: 'pt',
  },
  {
    name: 'João Pedro Rodrigues',
    email: 'joao.rodrigues@outlook.pt',
    phone: '+351 962 345 678',
    whatsapp: '+351 962 345 678',
    address: 'Quinta do Lago, Lote 4, Almancil',
    latitude: 37.0581, longitude: -8.0275,
    has_garden: true, has_pool: false, has_jacuzzi: false,
    garden_visit_frequency: 'seasonal', pool_visit_frequency: 'seasonal', jacuzzi_visit_frequency: 'seasonal',
    service_duration_minutes: 60,
    notes: 'Jardim de baixa manutenção. Rega automática instalada. Acesso pela garagem.',
    billing_type: 'monthly', monthly_rate: 95.00, payment_method: 'bank_transfer', preferred_language: 'pt',
    scheduled_transfer_day: 5,
  },
  {
    name: 'António Silva Costa',
    email: 'antoniocosta@sapo.pt',
    phone: '+351 934 456 789',
    whatsapp: '+351 934 456 789',
    address: 'Vilamoura, Rua do Golfe 23, Loulé',
    latitude: 37.0713, longitude: -8.1231,
    has_garden: true, has_pool: true, has_jacuzzi: true,
    garden_visit_frequency: 'once_monthly', pool_visit_frequency: 'once_monthly', jacuzzi_visit_frequency: 'seasonal',
    pool_length: 10.0, pool_width: 5.0, pool_min_depth: 1.4, pool_max_depth: 2.2,
    jacuzzi_length: 2.2, jacuzzi_width: 2.0, jacuzzi_depth: 0.9,
    service_duration_minutes: 150,
    notes: 'Moradia de luxo. Jardim formal com sebe aparada. Jacuzzi exterior coberto. Cão pastor alemão no jardim.',
    billing_type: 'monthly', monthly_rate: 280.00, payment_method: 'bank_transfer', preferred_language: 'pt',
    scheduled_transfer_day: 1,
  },
  {
    name: 'Susana Margarida Lopes',
    email: 'susanalopes@gmail.com',
    phone: '+351 926 567 890',
    whatsapp: '+351 926 567 890',
    address: 'Rua dos Pinheiros 7, Quarteira',
    latitude: 37.0662, longitude: -8.1003,
    has_garden: true, has_pool: false, has_jacuzzi: false,
    garden_visit_frequency: 'seasonal', pool_visit_frequency: 'seasonal', jacuzzi_visit_frequency: 'seasonal',
    service_duration_minutes: 45,
    notes: 'Jardim pequeno mas bem cuidado. Lavanda e alecrim. Rega manual.',
    billing_type: 'monthly', monthly_rate: 75.00, payment_method: 'mbway', preferred_language: 'pt',
  },
  {
    name: 'Carlos Alberto Mendes',
    email: 'carlos.mendes@netcabo.pt',
    phone: '+351 963 678 901',
    whatsapp: null,
    address: 'Urbanização Vale do Lobo, Lote 18, Almancil',
    latitude: 37.0517, longitude: -8.0502,
    has_garden: true, has_pool: true, has_jacuzzi: false,
    garden_visit_frequency: 'seasonal', pool_visit_frequency: 'once_monthly', jacuzzi_visit_frequency: 'seasonal',
    pool_length: 9.0, pool_width: 4.5, pool_min_depth: 1.2, pool_max_depth: 1.8,
    service_duration_minutes: 120,
    notes: 'Casa de férias. Normalmente vazio de outubro a março. Verificar estado quando chega o verão.',
    billing_type: 'monthly', monthly_rate: 180.00, payment_method: 'cash', preferred_language: 'pt',
  },
  {
    name: 'Ana Paula Sousa',
    email: 'anapaula.sousa@gmail.com',
    phone: '+351 912 789 012',
    whatsapp: '+351 912 789 012',
    address: 'Rua do Mar 3, Ferragudo, Lagoa',
    latitude: 37.1023, longitude: -8.5301,
    has_garden: true, has_pool: false, has_jacuzzi: false,
    garden_visit_frequency: 'on_demand', pool_visit_frequency: 'seasonal', jacuzzi_visit_frequency: 'seasonal',
    service_duration_minutes: 60,
    notes: 'Chama quando precisa. Geralmente de 6 em 6 semanas. Jardim costeiro com salsa e horta.',
    billing_type: 'per_visit', per_visit_rate: 55.00, payment_method: 'mbway', preferred_language: 'pt',
  },
  {
    name: 'Rui Manuel Pereira',
    email: 'rui.pereira@hotmail.com',
    phone: '+351 968 890 123',
    whatsapp: '+351 968 890 123',
    address: 'Rua das Acácias 31, Montenegro, Faro',
    latitude: 37.0418, longitude: -7.9721,
    has_garden: true, has_pool: true, has_jacuzzi: false,
    garden_visit_frequency: 'seasonal', pool_visit_frequency: 'seasonal', jacuzzi_visit_frequency: 'seasonal',
    pool_length: 7.0, pool_width: 3.5, pool_min_depth: 1.2, pool_max_depth: 1.8,
    service_duration_minutes: 90,
    notes: 'Piscina com sistema de sal. Jardim com gramado e palmeiras.',
    billing_type: 'monthly', monthly_rate: 165.00, payment_method: 'bank_transfer', preferred_language: 'pt',
    scheduled_transfer_day: 8,
  },
  {
    name: 'Filomena Graça Nunes',
    email: 'filomena.nunes@gmail.com',
    phone: '+351 924 901 234',
    whatsapp: '+351 924 901 234',
    address: 'Avenida da Liberdade 14, 2º Esq., Portimão',
    latitude: 37.1359, longitude: -8.5375,
    has_garden: true, has_pool: false, has_jacuzzi: false,
    garden_visit_frequency: 'once_monthly', pool_visit_frequency: 'seasonal', jacuzzi_visit_frequency: 'seasonal',
    service_duration_minutes: 45,
    notes: 'Terraço com vasos e canteiros. Rua estreita, estacionar na lateral.',
    billing_type: 'monthly', monthly_rate: 60.00, payment_method: 'mbway', preferred_language: 'pt',
  },
  {
    name: 'Peter Hartmann',
    email: 'p.hartmann@gmx.de',
    phone: '+49 170 234 5678',
    whatsapp: '+49 170 234 5678',
    address: 'Golden Triangle, Quinta do Lago, Almancil',
    latitude: 37.0543, longitude: -8.0389,
    has_garden: true, has_pool: true, has_jacuzzi: true,
    garden_visit_frequency: 'once_monthly', pool_visit_frequency: 'once_monthly', jacuzzi_visit_frequency: 'once_monthly',
    pool_length: 12.0, pool_width: 6.0, pool_min_depth: 1.5, pool_max_depth: 2.5,
    jacuzzi_length: 2.5, jacuzzi_width: 2.2, jacuzzi_depth: 1.0,
    service_duration_minutes: 180,
    notes: 'German client. Only in Portugal May-September. Full property management needed. High-end villa.',
    billing_type: 'monthly', monthly_rate: 350.00, payment_method: 'bank_transfer', preferred_language: 'en',
    scheduled_transfer_day: 10,
  },
  {
    name: 'Margaret Williams',
    email: 'margaret.williams@btinternet.com',
    phone: '+44 7890 123456',
    whatsapp: '+44 7890 123456',
    address: 'Rua da Barrosa 8, Carvoeiro, Lagoa',
    latitude: 37.0994, longitude: -8.4701,
    has_garden: true, has_pool: true, has_jacuzzi: false,
    garden_visit_frequency: 'seasonal', pool_visit_frequency: 'seasonal', jacuzzi_visit_frequency: 'seasonal',
    pool_length: 8.0, pool_width: 4.0, pool_min_depth: 1.2, pool_max_depth: 1.9,
    service_duration_minutes: 90,
    notes: 'British client, resident year-round. Prefers communication in English. Loves the garden. Pool with overflow system.',
    billing_type: 'monthly', monthly_rate: 195.00, payment_method: 'bank_transfer', preferred_language: 'en',
    scheduled_transfer_day: 15,
  },
  {
    name: 'Luísa Beatriz Tavares',
    email: 'luisatavares@gmail.com',
    phone: '+351 913 012 345',
    whatsapp: '+351 913 012 345',
    address: 'Rua Infante D. Henrique 22, Lagos',
    latitude: 37.1046, longitude: -8.6722,
    has_garden: true, has_pool: false, has_jacuzzi: false,
    garden_visit_frequency: 'on_demand', pool_visit_frequency: 'seasonal', jacuzzi_visit_frequency: 'seasonal',
    service_duration_minutes: 60,
    notes: 'Paga à hora. Jardim médio com horta. Gosta de acompanhar o trabalho.',
    billing_type: 'hourly', hourly_rate: 25.00, payment_method: 'mbway', preferred_language: 'pt',
  },
  {
    name: 'Paulo Jorge Matos',
    email: 'paulo.matos@sapo.pt',
    phone: '+351 967 123 456',
    whatsapp: null,
    address: 'Rua dos Eucaliptos 5, Guia, Albufeira',
    latitude: 37.1259, longitude: -8.2803,
    has_garden: true, has_pool: true, has_jacuzzi: false,
    garden_visit_frequency: 'seasonal', pool_visit_frequency: 'once_monthly', jacuzzi_visit_frequency: 'seasonal',
    pool_length: 6.0, pool_width: 3.0, pool_min_depth: 1.0, pool_max_depth: 1.6,
    service_duration_minutes: 75,
    notes: 'Prefere sempre numerário. Piscina pequena, fácil manutenção. Jardim com olival.',
    billing_type: 'monthly', monthly_rate: 140.00, payment_method: 'cash', preferred_language: 'pt',
  },
  {
    name: 'Teresa Cláudia Barros',
    email: 'teresa.barros@outlook.pt',
    phone: '+351 921 234 567',
    whatsapp: '+351 921 234 567',
    address: 'Rua do Moinho 9, Alvor, Portimão',
    latitude: 37.1222, longitude: -8.5942,
    has_garden: true, has_pool: false, has_jacuzzi: false,
    garden_visit_frequency: 'seasonal', pool_visit_frequency: 'seasonal', jacuzzi_visit_frequency: 'seasonal',
    service_duration_minutes: 60,
    notes: 'Jardim com bougainvillea e morangueiros. Tem sistema de rega temporizador.',
    billing_type: 'monthly', monthly_rate: 85.00, payment_method: 'mbway', preferred_language: 'pt',
  },
  {
    name: 'Francisco Joaquim Santos',
    email: 'fjsantos@gmail.com',
    phone: '+351 935 345 678',
    whatsapp: '+351 935 345 678',
    address: 'Rua do Sobreiro 17, Mexilhoeira Grande, Portimão',
    latitude: 37.1607, longitude: -8.5609,
    has_garden: true, has_pool: true, has_jacuzzi: false,
    garden_visit_frequency: 'seasonal', pool_visit_frequency: 'seasonal', jacuzzi_visit_frequency: 'seasonal',
    pool_length: 11.0, pool_width: 5.5, pool_min_depth: 1.3, pool_max_depth: 2.1,
    service_duration_minutes: 120,
    notes: 'Propriedade rural grande. Piscina com aquecimento solar. Cobrado à hora por visita.',
    billing_type: 'hourly', hourly_rate: 30.00, payment_method: 'bank_transfer', preferred_language: 'pt',
  },
  {
    name: 'Isabel Cristina Monteiro',
    email: 'isabel.monteiro@gmail.com',
    phone: '+351 914 456 789',
    whatsapp: '+351 914 456 789',
    address: 'Rua dos Laranjeiros 4, Estômbar, Lagoa',
    latitude: 37.1422, longitude: -8.5072,
    has_garden: true, has_pool: false, has_jacuzzi: true,
    garden_visit_frequency: 'seasonal', pool_visit_frequency: 'seasonal', jacuzzi_visit_frequency: 'once_monthly',
    jacuzzi_length: 2.0, jacuzzi_width: 1.8, jacuzzi_depth: 0.85,
    service_duration_minutes: 75,
    notes: 'Jacuzzi interior na suite. Jardim mediterrâneo com suculentas e pedra. Muito organizada.',
    billing_type: 'monthly', monthly_rate: 110.00, payment_method: 'mbway', preferred_language: 'pt',
  },
];

async function run() {
  for (const c of clients) {
    await pool.query(`
      INSERT INTO clients (
        user_id, name, email, phone, whatsapp, address,
        latitude, longitude,
        has_garden, has_pool, has_jacuzzi,
        garden_visit_frequency, pool_visit_frequency, jacuzzi_visit_frequency,
        pool_length, pool_width, pool_min_depth, pool_max_depth,
        jacuzzi_length, jacuzzi_width, jacuzzi_depth,
        service_duration_minutes, notes,
        billing_type, monthly_rate, hourly_rate, per_visit_rate,
        payment_method, preferred_language, scheduled_transfer_day
      ) VALUES (
        $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,
        $15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30
      )
    `, [
      USER_ID,
      c.name, c.email, c.phone, c.whatsapp ?? null, c.address,
      c.latitude, c.longitude,
      c.has_garden, c.has_pool, c.has_jacuzzi,
      c.garden_visit_frequency, c.pool_visit_frequency, c.jacuzzi_visit_frequency,
      c.pool_length ?? null, c.pool_width ?? null, c.pool_min_depth ?? null, c.pool_max_depth ?? null,
      c.jacuzzi_length ?? null, c.jacuzzi_width ?? null, c.jacuzzi_depth ?? null,
      c.service_duration_minutes, c.notes ?? null,
      c.billing_type, c.monthly_rate ?? null, c.hourly_rate ?? null, c.per_visit_rate ?? null,
      c.payment_method, c.preferred_language, c.scheduled_transfer_day ?? null,
    ]);
    console.log('  OK:', c.name);
  }

  const result = await pool.query('SELECT id, name, billing_type, monthly_rate, hourly_rate, per_visit_rate, payment_method FROM clients ORDER BY id');
  console.log('\n=== Clientes na BD ===');
  result.rows.forEach(r => {
    const rate = r.monthly_rate ? r.monthly_rate + ' EUR/mês'
                 : r.hourly_rate ? r.hourly_rate + ' EUR/h'
                 : r.per_visit_rate ? r.per_visit_rate + ' EUR/visita'
                 : '-';
    console.log(`  #${r.id} ${r.name} | ${r.billing_type} | ${rate} | ${r.payment_method}`);
  });

  await pool.end();
}

run().catch(e => { console.error('ERRO:', e.message); pool.end(); });
